[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "ipython>=9.15.0",
    "lazy-loader>=0.5",
    "matplotlib>=3.11.0",
    "pandas>=3.0.3",
    "pint>=0.25.3",
    "pluggy>=1.6.0",
    "pyautogui>=0.9.54",
    "pyserial>=3.5",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "scipy>=1.18.0",
    "traitlets>=5.15.1",
    "tzlocal>=5.4.4",
    "watchdog>=6.0.0",
    "zmq>=0.0.0",
]
